export { removeInitialCover } from './modules/removeInitialCover.js'
export { setAdjustVh } from './modules/setAdjustVh'
export { setDeep } from './modules/setDeep'
export { setIn } from './modules/setIn'
export { setModal } from './modules/setModal'
export { setSmoothScroll } from './modules/setSmoothScroll'
export { setSpMenu } from './modules/setSpMenu'
export { startAnimation } from './modules/startAnimation.js'
