// This file will be generated by the backend types generation process
// It exports Supabase types for use across the monorepo

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Types will be generated here
}